### ISSUE TITLE
ERROR！！！！ NO such file

### ISSUE THREAD

**Issue by winckietri** [bmatthiesen/deep-EE-opt#1]
unable to open file: name = '../../data/dset_final.h5', errno = 2, error message = 'No such file or directory'

**Comment by bmatthiesen** [comment]
This file needs to be generated first. Please read `README.md` in `src/DL`.

**Comment by klb2** [comment]
The script `src/DL/prepareDset.py` contained a wrong path. This is fixed in 1b09c73ba4569cd30d95d691b0e7f913e4d368ad.

Also please note that we provide the files `data/dset4.h5` and `data/dset7.h5` for the four user and seven user scenario, respectively. It is therefore not necessary to run `prepareDset.py`
